version: "3.7"

services:
  baseproject:
    container_name: baseproject_app
    build:
      context: .
      dockerfile: Dockerfile
    
    environment:
      - ENVIRONMENT=dev
    
    ports:
      - "4200:4200"
    volumes:
      - .:/code
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge
